package io.github.levitasorg.validators.gstin;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.*;

/**
 * Tests for {@link GstinValidator}.
 */
class GstinValidatorTest {

    // --- isValid() null/empty/whitespace ---

    @Test
    void isValid_null_returnsFalse() {
        assertThat(GstinValidator.isValid(null)).isFalse();
    }

    @Test
    void isValid_empty_returnsFalse() {
        assertThat(GstinValidator.isValid("")).isFalse();
    }

    @Test
    void isValid_whitespace_returnsFalse() {
        assertThat(GstinValidator.isValid("   ")).isFalse();
    }

    // --- isValid() wrong length ---

    @Test
    void isValid_tooShort14Chars_returnsFalse() {
        assertThat(GstinValidator.isValid("29AAAAA0000A1Z")).isFalse();
    }

    @Test
    void isValid_tooLong16Chars_returnsFalse() {
        assertThat(GstinValidator.isValid("29AAAAA0000A1ZXX")).isFalse();
    }

    // --- isValid() lowercase ---

    @Test
    void isValid_lowercase_returnsFalse() {
        String lower = TestGstinGenerator.GSTIN_KA_1.toLowerCase();
        assertThat(GstinValidator.isValid(lower)).isFalse();
    }

    // --- isValid() invalid state codes ---

    @ParameterizedTest
    @ValueSource(strings = {"00", "39", "40", "50", "96", "98"})
    void isValid_invalidStateCodes_returnsFalse(String invalidCode) {
        // Build a syntactically plausible 15-char string with invalid state code
        String candidate = invalidCode + "AAAAA0000A1ZX";
        // Pad/truncate to 15 chars if needed
        if (candidate.length() < 15) candidate = candidate + "A";
        assertThat(GstinValidator.isValid(candidate)).isFalse();
    }

    // --- isValid() valid format but wrong checksum ---

    @Test
    void isValid_validFormatWrongChecksum_returnsFalse() {
        String valid = TestGstinGenerator.GSTIN_KA_1;
        // Flip last character
        char lastChar = valid.charAt(14);
        char wrongChar = (lastChar == '0') ? '1' : '0';
        String invalid = valid.substring(0, 14) + wrongChar;
        assertThat(GstinValidator.isValid(invalid)).isFalse();
    }

    // --- isValid() known valid GSTINs ---

    /**
     * Pinned external test vector: {@code 29AAACB1234C1ZB}.
     *
     * <p>This GSTIN was independently verified by computing the checksum over the first 14
     * characters ({@code 29AAACB1234C1Z}):
     * <pre>
     *   sum = 169  →  checksum_value = (36 − (169 % 36)) % 36 = 11  →  ALPHABET[11] = 'B'
     * </pre>
     * It is used as an external reference to guard against algorithm regressions.
     */
    @Test
    void isValid_pinnedExternalVector_returnsTrue() {
        assertThat(GstinValidator.isValid("29AAACB1234C1ZB")).isTrue();
    }

    @Test
    void isValid_pinnedExternalVector_wrongChecksum_returnsFalse() {
        // '5' is not the correct checksum for this prefix — verifies checksum is enforced
        assertThat(GstinValidator.isValid("29AAACB1234C1Z5")).isFalse();
    }

    /**
     * AntiLabs note: these test vectors are generated by {@link TestGstinGenerator} which uses
     * {@link GstinValidator#computeChecksum} internally, making them self-referential.
     * They confirm internal consistency but NOT correctness against real GST registrations.
     * See {@link #isValid_pinnedExternalVector_returnsTrue()} for an externally verified vector.
     */
    @Test
    void isValid_generatedGstins_allValid() {
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_KA_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_MH_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_DL_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_TN_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_GJ_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_UP_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_WB_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_RJ_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_AP_1)).isTrue();
        assertThat(GstinValidator.isValid(TestGstinGenerator.GSTIN_TS_1)).isTrue();
    }

    // --- parse() ---

    @Test
    void parse_null_throwsIllegalArgumentException() {
        assertThatThrownBy(() -> GstinValidator.parse(null))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void parse_invalid_throwsIllegalArgumentException() {
        assertThatThrownBy(() -> GstinValidator.parse("INVALID"))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void parse_validGstin_extractsStateCorrectly() {
        GstinInfo info = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        assertThat(info.getStateCode()).isEqualTo(StateCode.KARNATAKA);
        assertThat(info.getStateCode().getDisplayName()).isEqualTo("Karnataka");
    }

    @Test
    void parse_validGstin_extractsPanCorrectly() {
        GstinInfo info = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        assertThat(info.getPan()).isEqualTo("AAAAA0000A");
    }

    @Test
    void parse_validGstin_extractsEntityCodeCorrectly() {
        GstinInfo info = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        assertThat(info.getEntityCode()).isEqualTo("1");
    }

    @Test
    void parse_validGstin_entityTypeIsRegular() {
        GstinInfo info = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        assertThat(info.getEntityType()).isEqualTo(EntityType.REGULAR);
    }

    @Test
    void parse_validGstin_checksumCharMatches() {
        String gstin = TestGstinGenerator.GSTIN_MH_1;
        GstinInfo info = GstinValidator.parse(gstin);
        assertThat(info.getChecksumChar()).isEqualTo(gstin.charAt(14));
    }

    @Test
    void parse_result_gstinFieldMatchesInput() {
        String gstin = TestGstinGenerator.GSTIN_DL_1;
        assertThat(GstinValidator.parse(gstin).getGstin()).isEqualTo(gstin);
    }

    // --- extractStateCode() ---

    @Test
    void extractStateCode_null_returnsEmpty() {
        assertThat(GstinValidator.extractStateCode(null)).isEmpty();
    }

    @Test
    void extractStateCode_shortString_returnsEmpty() {
        assertThat(GstinValidator.extractStateCode("2")).isEmpty();
    }

    @Test
    void extractStateCode_validPrefix_returnsState() {
        assertThat(GstinValidator.extractStateCode("29XXXXXXXXX"))
                .contains(StateCode.KARNATAKA);
    }

    @Test
    void extractStateCode_invalidStateCode_returnsEmpty() {
        assertThat(GstinValidator.extractStateCode("00XXXXXXXXX")).isEmpty();
    }

    // --- extractPan() ---

    @Test
    void extractPan_null_returnsEmpty() {
        assertThat(GstinValidator.extractPan(null)).isEmpty();
    }

    @Test
    void extractPan_shortString_returnsEmpty() {
        assertThat(GstinValidator.extractPan("29AAAA")).isEmpty();
    }

    @Test
    void extractPan_longerString_extractsCorrectly() {
        String gstin = TestGstinGenerator.GSTIN_KA_1;
        Optional<String> pan = GstinValidator.extractPan(gstin);
        assertThat(pan).contains("AAAAA0000A");
    }

    // --- isValidFormat() ---

    @Test
    void isValidFormat_null_returnsFalse() {
        assertThat(GstinValidator.isValidFormat(null)).isFalse();
    }

    @Test
    void isValidFormat_wrongChecksum_stillValidFormat() {
        String valid = TestGstinGenerator.GSTIN_KA_1;
        // Corrupt checksum but keep format valid
        char lastChar = valid.charAt(14);
        // Replace last char with a different alphanumeric in the GSTIN alphabet
        char altChar = (lastChar == '0') ? '1' : '0';
        String wrongChecksum = valid.substring(0, 14) + altChar;
        // Format check passes, but checksum is wrong
        assertThat(GstinValidator.isValidFormat(wrongChecksum)).isTrue();
        assertThat(GstinValidator.isValid(wrongChecksum)).isFalse();
    }

    // --- computeChecksum() ---

    @Test
    void computeChecksum_null_throws() {
        assertThatThrownBy(() -> GstinValidator.computeChecksum(null))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void computeChecksum_wrongLength_throws() {
        assertThatThrownBy(() -> GstinValidator.computeChecksum("29AAAAA0000A1"))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void computeChecksum_matchesLastCharOfGenerated() {
        String gstin = TestGstinGenerator.GSTIN_KA_1;
        char computed = GstinValidator.computeChecksum(gstin.substring(0, 14));
        assertThat(computed).isEqualTo(gstin.charAt(14));
    }

    // --- Thread safety ---

    @Test
    void threadSafety_1000ParallelValidations_noExceptions() throws Exception {
        String gstin = TestGstinGenerator.GSTIN_KA_1;
        int threads = 50;
        int callsPerThread = 20;
        ExecutorService executor = Executors.newFixedThreadPool(threads);
        AtomicInteger failureCount = new AtomicInteger(0);
        CountDownLatch latch = new CountDownLatch(1);
        List<Future<?>> futures = new ArrayList<>();

        for (int i = 0; i < threads; i++) {
            futures.add(executor.submit(() -> {
                try {
                    latch.await();
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                for (int j = 0; j < callsPerThread; j++) {
                    try {
                        boolean result = GstinValidator.isValid(gstin);
                        if (!result) failureCount.incrementAndGet();
                    } catch (Exception ex) {
                        failureCount.incrementAndGet();
                    }
                }
            }));
        }
        latch.countDown();
        for (Future<?> f : futures) {
            f.get();
        }
        executor.shutdown();
        assertThat(failureCount.get()).isZero();
    }

    // --- GstinInfo equals/hashCode/toString ---

    @Test
    void gstinInfo_equalsAndHashCode() {
        GstinInfo a = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        GstinInfo b = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        assertThat(a).isEqualTo(b);
        assertThat(a.hashCode()).isEqualTo(b.hashCode());
    }

    @Test
    void gstinInfo_notEqualToDifferentGstin() {
        GstinInfo a = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        GstinInfo b = GstinValidator.parse(TestGstinGenerator.GSTIN_MH_1);
        assertThat(a).isNotEqualTo(b);
    }

    @Test
    void gstinInfo_toStringContainsGstin() {
        GstinInfo info = GstinValidator.parse(TestGstinGenerator.GSTIN_KA_1);
        assertThat(info.toString()).contains(TestGstinGenerator.GSTIN_KA_1);
    }

    // --- StateCode enum ---

    @Test
    void stateCode_fromCode_knownCode_returnsCorrect() {
        assertThat(StateCode.fromCode("29")).contains(StateCode.KARNATAKA);
        assertThat(StateCode.fromCode("07")).contains(StateCode.DELHI);
        assertThat(StateCode.fromCode("27")).contains(StateCode.MAHARASHTRA);
    }

    @Test
    void stateCode_fromCode_null_returnsEmpty() {
        assertThat(StateCode.fromCode(null)).isEmpty();
    }

    @Test
    void stateCode_fromCode_unknownCode_returnsEmpty() {
        assertThat(StateCode.fromCode("00")).isEmpty();
        assertThat(StateCode.fromCode("39")).isEmpty();
        assertThat(StateCode.fromCode("98")).isEmpty();
    }
}
